---
- name: show output and other user level commands
  hosts: all_routers
  gather_facts: false
  connection: local

  tasks:
    - name: run multiple commands on the remote nodes
      ios_command:
        commands:
          - show version
          - show ip int br

      register: print_output

    - debug: var=print_output.stdout_lines
